import {q,tx,id,secret,hash,fail} from './db.mjs';
import {rateLimit} from './redis.mjs';
import {ledger} from './accounting.mjs';
const base=()=>process.env.APP_URL?.replace(/\/$/,'');
export function cookies(req){return Object.fromEntries((req.headers.cookie||'').split(';').map(x=>{const i=x.indexOf('=');return [x.slice(0,i).trim(),decodeURIComponent(x.slice(i+1))];}));}
export function cookie(res,name,value,seconds){res.cookie(name,value,{httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'lax',maxAge:seconds*1000,path:'/'});}
export async function user(req){const s=cookies(req).mint_session;if(!s)fail(401,'authentication_required','Sign in to continue.');const u=(await q('SELECT u.* FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.hash=$1 AND s.expires>now()',[hash(s)])).rows[0];if(!u||u.suspended)fail(401,'authentication_required','Sign in to continue.');return u;}
export async function admin(req){const u=await user(req);if(u.role!=='admin'||!(process.env.ADMIN_X_IDS||'').split(',').map(x=>x.trim()).includes(u.x_id))fail(403,'forbidden','Admin access required.');return u;}
export async function reward(userId){return tx(async c=>{const s=(await c.query('SELECT data FROM settings WHERE id=1 FOR UPDATE')).rows[0].data;const u=(await c.query('SELECT * FROM users WHERE id=$1 FOR UPDATE',[userId])).rows[0];if(!s.promoEnabled||!u?.ip_hash||!u.device_hash||!u.x_created_at||Date.now()-new Date(u.x_created_at)<Number(s.promoMinAgeDays||0)*86400000)return false;
// The signup grant belongs to the verified X identity. IP and device hashes are
// retained for audit, but cannot reject another real X account on a shared
// browser, home network, school, office, VPN, or mobile carrier. The claim rows
// and ledger references keep the grant idempotent for each X account.
const prior=(await c.query('SELECT 1 FROM promo_claims WHERE x_id=$1 OR user_id=$2 OR ($3::text IS NOT NULL AND email=$3)',[u.x_id,u.id,u.email||null])).rowCount;if(prior)return false;
const held=(await c.query("SELECT COALESCE(sum(max_weighted),0) n FROM reservations WHERE state IN ('reserved','review')")).rows[0];const pending=(await c.query("SELECT COALESCE(sum(base_tokens),0) n FROM orders WHERE state='pending'")).rows[0];const liabilities=(await c.query('SELECT COALESCE(sum(base_tokens+promo_tokens),0) n FROM users')).rows[0];if(BigInt(liabilities.n)+BigInt(held.n)+BigInt(pending.n)+BigInt(s.promoTokens)>BigInt(s.inventory)*8n/10n)return false;
await c.query('INSERT INTO promo_claims(x_id,email,user_id,ip_hash,device_hash) VALUES($1,$2,$3,$4,$5)',[u.x_id,u.email||null,u.id,u.ip_hash,u.device_hash]);await c.query("UPDATE users SET promo_tokens=$2,promo_micro=$3,promo_expires=now()+interval '7 days' WHERE id=$1",[u.id,s.promoTokens,s.promoMicro]);await ledger(c,u.id,'promo-token',s.promoTokens,'reward:'+u.x_id);await ledger(c,u.id,'promo-dollar',s.promoMicro,'reward:'+u.x_id);return true;});}
export function mountAuth(app){
app.get('/api/auth/x',async(req,res)=>{if(!process.env.X_CLIENT_ID||!process.env.X_CLIENT_SECRET||!base())return res.redirect('/signin?error=x_not_configured');await rateLimit('oauth:'+hash(req.ip||''),10,600);const state=secret(),verifier=secret(),device=cookies(req).mint_device||secret();cookie(res,'mint_device',device,86400*365);cookie(res,'mint_oauth',state,600);await q("INSERT INTO challenges(hash,kind,data,expires) VALUES($1,'oauth',$2,now()+interval '10 minutes')",[hash(state),{verifier,ip:hash((process.env.ABUSE_HASH_SECRET||secret())+(req.ip||'')),device:hash(device)}]);const url=new URL('https://x.com/i/oauth2/authorize');url.search=new URLSearchParams({response_type:'code',client_id:process.env.X_CLIENT_ID,redirect_uri:base()+'/api/auth/x/callback',scope:'tweet.read users.read',state,code_challenge:Buffer.from(hash(verifier),'hex').toString('base64url'),code_challenge_method:'S256'}).toString();res.redirect(url.toString());});
app.get('/api/auth/x/callback',async(req,res)=>{const {state,code}=req.query;if(typeof state!=='string'||typeof code!=='string'||state!==cookies(req).mint_oauth)fail(400,'invalid_state','Invalid login state. Start sign-in again.');const c=(await q("DELETE FROM challenges WHERE hash=$1 AND kind='oauth' AND expires>now() RETURNING data",[hash(state)])).rows[0];cookie(res,'mint_oauth','',0);if(!c)fail(400,'expired_login','Sign-in expired.');const tokenResponse=await fetch('https://api.x.com/2/oauth2/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded',Authorization:'Basic '+Buffer.from(process.env.X_CLIENT_ID+':'+process.env.X_CLIENT_SECRET).toString('base64')},body:new URLSearchParams({code,grant_type:'authorization_code',redirect_uri:base()+'/api/auth/x/callback',code_verifier:c.data.verifier}),signal:AbortSignal.timeout(15000)});if(!tokenResponse.ok)fail(502,'x_auth_failed','X sign-in could not be completed.');const token=await tokenResponse.json();const profileResponse=await fetch('https://api.x.com/2/users/me?user.fields=created_at,profile_image_url',{headers:{Authorization:'Bearer '+token.access_token},signal:AbortSignal.timeout(15000)});if(!profileResponse.ok)fail(502,'x_profile_failed','Unable to verify your X account.');const {data}=await profileResponse.json();if(!data?.id)fail(502,'x_profile_failed','X returned an invalid profile.');const role=(process.env.ADMIN_X_IDS||'').split(',').map(x=>x.trim()).includes(data.id)?'admin':'user';const u=(await q('INSERT INTO users(id,x_id,username,avatar_url,role,x_created_at,ip_hash,device_hash) VALUES($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT(x_id) DO UPDATE SET username=excluded.username,avatar_url=COALESCE(excluded.avatar_url,users.avatar_url),role=excluded.role RETURNING *',[id(),data.id,data.username,data.profile_image_url||null,role,data.created_at||null,c.data.ip,c.data.device])).rows[0];const session=secret();await q("INSERT INTO sessions(hash,user_id,expires) VALUES($1,$2,now()+interval '7 days')",[hash(session),u.id]);cookie(res,'mint_session',session,7*86400);await reward(u.id);res.redirect('/dashboard');});
app.post('/api/auth/logout',async(req,res)=>{await q('DELETE FROM sessions WHERE hash=$1',[hash(cookies(req).mint_session||'')]);cookie(res,'mint_session','',0);res.json({ok:true});});
}
