import pg from 'pg';
import {readFile} from 'node:fs/promises';
import {randomUUID,createHash,randomBytes,createCipheriv,createDecipheriv} from 'node:crypto';
export const pool=process.env.DATABASE_URL?new pg.Pool({connectionString:process.env.DATABASE_URL,max:15,connectionTimeoutMillis:5000}):null;
export const id=()=>randomUUID();
export const secret=()=>randomBytes(32).toString('base64url');
export const hash=s=>createHash('sha256').update(s).digest('hex');
export function fail(status,code,message){throw Object.assign(new Error(message),{status,code});}
export async function q(sql,args=[]){if(!pool)fail(503,'database_unconfigured','Database is not configured.');return pool.query(sql,args);}
export async function tx(fn){if(!pool)fail(503,'database_unconfigured','Database is not configured.');const c=await pool.connect();try{await c.query('BEGIN');const r=await fn(c);await c.query('COMMIT');return r;}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}
function encryptionKey(){const key=Buffer.from(process.env.ENCRYPTION_KEY||'','base64');if(key.length!==32)fail(503,'encryption_unconfigured','Configure a 32-byte ENCRYPTION_KEY.');return key;}
export function encrypt(text){const iv=randomBytes(12),c=createCipheriv('aes-256-gcm',encryptionKey(),iv);return Buffer.concat([iv,c.update(text),c.final(),c.getAuthTag()]).toString('base64');}
export function decrypt(value){const b=Buffer.from(value,'base64'),d=createDecipheriv('aes-256-gcm',encryptionKey(),b.subarray(0,12));d.setAuthTag(b.subarray(-16));return Buffer.concat([d.update(b.subarray(12,-16)),d.final()]).toString();}
export const numbers=x=>JSON.parse(JSON.stringify(x,(_,v)=>typeof v==='bigint'?v.toString():v));
export async function initialize(){if(!pool)return;await q(await readFile(new URL('./schema.sql',import.meta.url),'utf8'));const seeds=[['MiMo V2.5','MiMo',.05],['Nemotron 3 Ultra','NVIDIA',.05],['Nemotron 3.5 Lightning','NVIDIA',.05],['Muse Spark 1.2','Muse',.05],['Qwen 3.7 Plus','Qwen',.1],['DeepSeek V4 Flash','DeepSeek',.1],['Qwen 3.7 Max','Qwen',.2],['GPT-5.6 Luna','OpenAI',.22],['Qwen 3.8 Max','Qwen',.3],['DeepSeek V4.1 Flash','DeepSeek',.3],['MiMo V2.5 Pro','MiMo',.3],['MiniMax M3','MiniMax',.45],['Composer 2.5 Fast','Cursor',.5],['GLM 5.3 Flash','Z.ai',.6],['DeepSeek V4 Pro','DeepSeek',.6],['GPT-5.4 Mini','OpenAI',.8],['Grok 4.6','xAI',.8],['Grok 4.5','xAI',.8],['Claude Haiku 4.5','Anthropic',.9],['Gemini Flash','Google',1],['GLM 5 Turbo','Z.ai',1.38],['GPT-5.6 Terra','OpenAI',1.5],['GPT-5.4','OpenAI',1.5],['Kimi K2.7 Code','Moonshot',1.5],['GLM 5.3','Z.ai',1.9],['Claude Sonnet 5','Anthropic',2],['Claude Sonnet 4.6','Anthropic',2],['Gemini 3.1 Pro','Google',2],['GPT-5.6 Sol','OpenAI',3],['GPT-5.5','OpenAI',3],['Claude Opus','Anthropic',4],['Kimi K3','Moonshot',5.5],['GPT-6 Astra','OpenAI',7.5],['Claude Fable','Anthropic',8]];
for(const [name,family,ratio] of seeds){const slug=name.toLowerCase().replace(/[^a-z0-9.]+/g,'-');await q('INSERT INTO models(id,name,family,upstream_id,ratio,premium,promo) VALUES($1,$2,$3,$1,$4,$5,$6) ON CONFLICT DO NOTHING',[slug,name,family,ratio,ratio>=3,ratio<=1]);}
if(process.env.UPSTREAM_API_KEY&&process.env.ENCRYPTION_KEY){const key=encrypt(process.env.UPSTREAM_API_KEY);await q("INSERT INTO providers(id,name,base_url,encrypted_key) VALUES('00000000-0000-4000-8000-000000000001','RelayModels',$1,$2) ON CONFLICT(id) DO UPDATE SET encrypted_key=excluded.encrypted_key,base_url=excluded.base_url",[process.env.UPSTREAM_BASE_URL||'https://api.relaymodels.com/v1',key]);}}
