import {JsonRpcProvider,verifyMessage,isAddress,parseEther,formatEther} from 'ethers';
import {q,tx,id,hash,secret,fail} from './db.mjs';
import {user} from './auth.mjs';
import {rateLimit} from './redis.mjs';
import {backedCredit} from './accounting.mjs';
export const chains=[{id:1,name:'Ethereum',symbol:'ETH',explorer:'https://etherscan.io',env:'ETHEREUM_RPC_URL'},{id:4663,name:'Robinhood',symbol:'ETH',explorer:'https://robinhoodchain.blockscout.com',env:'ROBINHOOD_RPC_URL'}];
const providers=new Map();export function rpc(chain){const info=chains.find(x=>x.id===Number(chain));if(!info||!process.env[info.env])fail(503,'chain_unconfigured','Payment network is not configured.');if(!providers.has(info.id))providers.set(info.id,new JsonRpcProvider(process.env[info.env]));return providers.get(info.id);}
export async function verifyInvoice(order,receipt,transaction,block,finalized){if(!receipt||!transaction||!block||!finalized)fail(409,'payment_pending','Payment is awaiting on-chain finality.');if(receipt.status!==1)fail(400,'payment_failed','The transaction failed.');if(receipt.blockNumber>finalized.number)fail(409,'payment_pending','Payment is awaiting on-chain finality.');if(transaction.from.toLowerCase()!==order.wallet.toLowerCase()||transaction.to?.toLowerCase()!==order.treasury.toLowerCase()||transaction.value!==BigInt(order.wei))fail(400,'payment_mismatch','Sender, receiving address or amount does not match the invoice.');const timestamp=block.timestamp*1000;if(timestamp<new Date(order.created_at).getTime()-15000||timestamp>new Date(order.expires).getTime())fail(400,'quote_expired','The payment was mined outside the quote window; contact support for review.');if(receipt.blockHash!==block.hash)fail(409,'payment_pending','Payment block is no longer canonical.');return true;}
export function mountPayments(app){
app.get('/api/payment/networks',(req,res)=>res.json(chains.map(({env,...c})=>({...c,configured:!!process.env[env]&&isAddress(process.env.PAYMENT_TREASURY_ADDRESS||'')}))));
app.post('/api/wallet/challenge',async(req,res)=>{const u=await user(req);await rateLimit('wallet:'+u.id,10,600);if(!isAddress(req.body.address))fail(400,'invalid_address','Choose a valid wallet address.');const nonce=secret(),message=`${new URL(process.env.APP_URL).host} wants to link your wallet for ModelMint payments.\n\nAddress: ${req.body.address}\nAccount: ${u.id}\nNonce: ${nonce}\nExpires in 5 minutes.\nThis signature does not authorize a transaction.`;await q("INSERT INTO challenges(hash,user_id,kind,data,expires) VALUES($1,$2,'wallet',$3,now()+interval '5 minutes')",[hash(nonce),u.id,{message,address:req.body.address}]);res.json({nonce,message});});
app.post('/api/wallet/verify',async(req,res)=>{const u=await user(req),{nonce,signature}=req.body;if(typeof nonce!=='string'||typeof signature!=='string')fail(400,'invalid_signature','Wallet signature is required.');const c=(await q("DELETE FROM challenges WHERE hash=$1 AND user_id=$2 AND kind='wallet' AND expires>now() RETURNING data",[hash(nonce),u.id])).rows[0];if(!c)fail(400,'challenge_expired','Wallet verification expired.');let signer;try{signer=verifyMessage(c.data.message,signature);}catch{fail(400,'invalid_signature','Invalid wallet signature.');}if(signer.toLowerCase()!==c.data.address.toLowerCase())fail(400,'invalid_signature','Wallet does not match.');await q('UPDATE users SET wallet=$2 WHERE id=$1',[u.id,signer.toLowerCase()]);res.json({wallet:signer});});
app.post('/api/payments/quote',async(req,res)=>{const u=await user(req);await rateLimit('quote:'+u.id,10,60);if(!u.wallet)fail(400,'wallet_required','Connect and verify your wallet first.');const pay=Number(req.body.pay),chain=Number(req.body.chainId);if(![5,10,25,50].includes(pay)||!chains.some(c=>c.id===chain))fail(400,'invalid_package','Choose a supported package and network.');const treasury=process.env.PAYMENT_TREASURY_ADDRESS;if(!isAddress(treasury||''))fail(503,'treasury_unconfigured','Payment receiving wallet is not configured.');const p=rpc(chain);if(Number((await p.getNetwork()).chainId)!==chain)fail(503,'rpc_mismatch','Payment network verification failed.');
const priceResponse=await fetch('https://api.coinbase.com/v2/prices/ETH-USD/spot',{signal:AbortSignal.timeout(10000),cache:'no-store'});if(!priceResponse.ok)fail(503,'price_unavailable','Unable to obtain a current ETH price.');const priceData=await priceResponse.json(),price=priceData.data?.amount;if(!/^\d+(\.\d+)?$/.test(price||'')||Number(price)<=0||priceData.data?.base!=='ETH'||priceData.data?.currency!=='USD')fail(503,'price_unavailable','ETH quote is unavailable.');const priceScaled=parseEther(price),wei=(BigInt(pay)*10n**36n+priceScaled-1n)/priceScaled;
const order=await tx(async c=>{const s=(await c.query('SELECT data FROM settings WHERE id=1 FOR UPDATE')).rows[0].data;if(!s.purchasing||s.shutdown||!s.baseTokensPerDollar)fail(503,'purchases_paused','Credit purchases are not open yet.');const liability=(await c.query('SELECT COALESCE(sum(base_tokens+promo_tokens),0) n FROM users')).rows[0];const held=(await c.query("SELECT COALESCE(sum(max_weighted),0) n FROM reservations WHERE state IN ('reserved','review')")).rows[0];const pending=(await c.query("SELECT COALESCE(sum(base_tokens),0) n FROM orders WHERE state='pending'")).rows[0];const base=BigInt(pay*2)*BigInt(s.baseTokensPerDollar);if(BigInt(liability.n)+BigInt(held.n)+BigInt(pending.n)+base>BigInt(s.inventory)*8n/10n)fail(409,'inventory_committed','Available credit capacity is committed. Try again later.');return (await c.query("INSERT INTO orders(id,user_id,chain_id,wallet,treasury,pay_usd,credit_micro,base_tokens,wei,quote_price,expires) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,now()+interval '10 minutes') RETURNING *",[id(),u.id,chain,u.wallet,treasury,pay,pay*2*1000000,String(base),String(wei),price])).rows[0];});res.json({...order,eth:formatEther(wei)});});
app.post('/api/payments/verify',async(req,res)=>{const u=await user(req);await rateLimit('payment:'+u.id,30,60);const {orderId,txHash}=req.body;if(!/^[0-9a-f-]{36}$/i.test(orderId||'')||!/^0x[0-9a-f]{64}$/i.test(txHash||''))fail(400,'invalid_transaction','A valid invoice ID and transaction hash are required.');const order=(await q('SELECT * FROM orders WHERE id=$1 AND user_id=$2',[orderId,u.id])).rows[0];if(!order)fail(404,'invoice_not_found','Invoice not found.');if(order.state==='paid')return res.json({ok:true,state:'paid'});const p=rpc(order.chain_id);if(Number((await p.getNetwork()).chainId)!==order.chain_id)fail(503,'rpc_mismatch','Incorrect RPC network.');const [receipt,transaction,finalized]=await Promise.all([p.getTransactionReceipt(txHash),p.getTransaction(txHash),p.getBlock('finalized')]);const block=receipt?await p.getBlock(receipt.blockNumber):null;await verifyInvoice(order,receipt,transaction,block,finalized);
await tx(async c=>{await c.query('SELECT data FROM settings WHERE id=1 FOR UPDATE');const locked=(await c.query('SELECT * FROM orders WHERE id=$1 FOR UPDATE',[order.id])).rows[0];if(locked.state==='paid')return;await c.query("UPDATE orders SET state='paid',tx_hash=$2,confirmed_at=now() WHERE id=$1",[order.id,txHash.toLowerCase()]);await backedCredit(c,u.id,BigInt(order.credit_micro),BigInt(order.base_tokens),order.id);});res.json({ok:true,state:'paid'});});
}
